### ISSUE TITLE
Cannot read property 'access_token' of undefined

### ISSUE THREAD

**Issue by elrodrix** [waleedahmad/NodeScheduler#1]
Hi. I have a problem when I want to post a photo. 

I have this error:

`/home/myhome/react_project/NodeScheduler/routes/scheduler.js:78
            access_token: page.access_token
                              ^
TypeError: Cannot read property 'access_token' of undefined
    at FB.api.pages (/home/myhome/react_project/NodeScheduler/routes/scheduler.js:78:31)`

I tried to print a console.log with the value 'page' and shows 'undefined'
You know why I have this error?.

btw: my facebook app is not activated yet, it's in development. This will be related to the problem?

**Comment by waleedahmad** [comment]
Hi. I forgot to validate the available pages select field in schedule form. I was able to reproduce this error by scheduling a post without selecting a page from the available pages dropdown list. It works when you schedule a post for an existing page. I'll add validation to available pages dropdown to stop scheduling posts without selecting a page.

**Comment by waleedahmad** [comment]
Fixed in https://github.com/waleedahmad/NodeScheduler/commit/3f14a44e163f18ea2fa6df4cf39e88f459754d99

**Comment by elrodrix** [comment]
@waleedahmad thank you very much for your fix. I have another question. Can I add the option to publish a photo in my personal account profile registered on facebook?. How could I achieve or add that option?. Thnk!

**Comment by waleedahmad** [comment]
When I was writing this scheduler, I tested publishing to user profiles and failed. To publish to user profiles, we need publish_actions permissions and it's deprecated. 

Read more about Facebook Policy changes [here](https://developers.facebook.com/blog/post/2018/04/24/new-facebook-platform-product-changes-policy-updates/)

> The publish_actions permission will be deprecated. This permission granted apps access to publish posts to Facebook as the logged in user. Apps created from today onwards will not have access to this permission. Apps created before today that have been previously approved to request publish_actions can continue to do so until August 1, 2018. No further apps will be approved to use publish_actions via app review. Developers currently utilizing publish_actions are encouraged to switch to Facebook's Share dialogs for web, iOS and Android. 

Now we're limited to use [Facebook's Share Dialog](https://developers.facebook.com/docs/sharing/reference/share-dialog). It only allows specific formats like links to be published.
